export const KURTAS=
[
    {
        id:1,
        item:'Kurtas',
        name:'Libas',
        description:'Block Print Sraight Kurta',
        price:1000,
        navid:1,
        image:'/assets/images/kurtasimg1.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        
    },
    {
        id:1,
        item:'Kurtas',
        name:'Libas',
        description:'Block Print Sraight Kurta',
        price:400,
        navid:2,
        image: '/assets/images/kurtasimg2.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:1,
        name:'Libas',
        item:'Kurtas',

        description:'Block Print Sraight Kurta',
        price:300,
        navid:3,
        image: '/assets/images/kurtasimg3.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },  
    {
        id:1,
        name:'Libas',
        item:'Kurtas',

        description:'Block Print Sraight Kurta',
        price:1200,
        navid:4,
        image: '/assets/images/kurtasimg4.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:1,
        name:'Libas',
        item:'Kurtas',

        description:'Block Print Sraight Kurta',
        price:1500,
        navid:5,
        image: '/assets/images/kurtasimg1.2.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:1,
        name:'Libas',
        item:'Kurtas',

        description:'Block Print Sraight Kurta',
        price:1200,
        navid:6,
        image: '/assets/images/kurtasimg2.1.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:2,
        name:'Libas',
        item:'tops',
        navid:1,
        description:'Block Print Sraight Kurta',
        price:1234,
        image: '/assets/images/tops1.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:2,
        name:'Libas',
        item:'tops',
        navid:2,

        description:'Block Print Sraight Kurta',
        price:3400,
        image: '/assets/images/tops2.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:2,
        name:'Libas',
        item:'tops',
        navid:3,

        description:'Block Print Sraight Kurta',
        price:1235,
        image: '/assets/images/tops3.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:2,
        name:'Libas',
        item:'tops',
        navid:4,

        description:'Block Print Sraight Kurta',
        price:2345,
        image: '/assets/images/tops4.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:2,
        name:'Libas',
        item:'tops',
        navid:5,
        description:'Block Print Sraight Kurta',
        price:400,
        image: '/assets/images/tops5.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:2,
        name:'Libas',
        item:'tops',
         description:'Block Print Sraight Kurta',
         navid:6,
        price:3456,
        image: '/assets/images/tops6.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:3,
        name:'Libas',
        item:'menstshirt',
        description:'Block Print Sraight Kurta',
        navid:1,
        price:500,
        image: '/assets/images/menstshirt1.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        


    },
    {
        id:3,
        name:'Libas',
        item:'menstshirt',
        navid:2,
        description:'Block Print Sraight Kurta',
        price:600,
        image: '/assets/images/menstshirt2.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:3,
        name:'Libas',
        item:'menstshirt',
        navid:3,
        description:'Block Print Sraight Kurta',
        price:700,
        image: '/assets/images/menstshirt3.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:3,
        name:'Libas',
        item:'menstshirt',
        navid:4,
        description:'Block Print Sraight Kurta',
        price:800,
        image: '/assets/images/menstshirt4.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:3,
        name:'Libas',
        item:'menstshirt',
        navid:5,
        description:'Block Print Sraight Kurta',
        price:900,
        image: '/assets/images/menstshirt5.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:3,
        name:'Libas',
        item:'menstshirt',
        navid:6,
        description:'Block Print Sraight Kurta',
        price:1000,
        image: '/assets/images/menstshirt6.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:4,
        name:'Libas',
        item:'dresses',
        navid:1,
        description:'Block Print Sraight Kurta',
        price:1100,
        image: '/assets/images/dresses1.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:4,
        name:'Libas',
        item:'dresses',
        navid:2,
        description:'Block Print Sraight Kurta',
        price:1200,
        image: '/assets/images/dresses2.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:4,
        name:'Libas',
        item:'dresses',
        navid:3,
        description:'Block Print Sraight Kurta',
        price:300,
        image: '/assets/images/dresses3.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:4,
        name:'Libas',
        item:'dresses',
        navid:4,
        description:'Block Print Sraight Kurta',
        price:400,
        image: '/assets/images/dresses4.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:4,
        name:'Libas',
        item:'dresses',
        navid:5,
        description:'Block Print Sraight Kurta',
        price:500,
        image: '/assets/images/dresses5.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:4,
        name:'Libas',
        item:'dresses',
        navid:6,
        description:'Block Print Sraight Kurta',
        price:120,
        image: '/assets/images/dresses6.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:5,
        name:'Libas',
        item:'casualtrousers',
        navid:1,
        description:'Block Print Sraight Kurta',
        price:300,
        image: '/assets/images/casualtrousers1.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:5,
        name:'Libas',
        item:'casualtrousers',
        navid:2,
        description:'Block Print Sraight Kurta',
        price:234,
        image: '/assets/images/casualtrousers2.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:5,
        name:'Libas',
        item:'casualtrousers',
        navid:3,
        description:'Block Print Sraight Kurta',
        price:456,
        image: '/assets/images/casualtrousers3.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:5,
        name:'Libas',
        item:'casualtrousers',
        navid:4,
        description:'Block Print Sraight Kurta',
        price:567,
        image: '/assets/images/casualtrousers4.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:5,
        name:'Libas',
        item:'casualtrousers',
        navid:5,
        description:'Block Print Sraight Kurta',
        price:4567,
        image: '/assets/images/casualtrousers5.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:5,
        name:'Libas',
        item:'casualtrousers',
        navid:6,
        description:'Block Print Sraight Kurta',
        price:7890,
        image: '/assets/images/casualtrousers6.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:6,
        name:'Libas',
        item:'casualshirts',
        navid:1,
         description:'Block Print Sraight Kurta',
        price:5678,
        image: '/assets/images/casualshirts1.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:6,
        name:'Libas',
        item:'casualshirts',
        navid:2,
        description:'Block Print Sraight Kurta',
        price:8907,
        image: '/assets/images/casualshirts2.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:6,
        name:'Libas',
        item:'casualshirts',
        navid:3,
        description:'Block Print Sraight Kurta',
        price:123,
        image: '/assets/images/casualshirts3.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:6,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'casualshirts',
        navid:4,
        price:456,
        image: '/assets/images/casualshirts4.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:6,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'casualshirts',
        navid:5,
        price:567,
        image: '/assets/images/casualshirts5.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:6,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'casualshirts',
        navid:6,
        price:7890,
        image: '/assets/images/casualshirts6.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:7,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'casualfootwear',
        navid:1,
        price:567,
        image: '/assets/images/casualfootwear1.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:7,
        name:'Libas',
        description:'Block Print Sraight Kurta',        
        item:'casualfootwear',
        navid:2,

        price:6786,
        image: '/assets/images/casualfootwear2.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:7,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'casualfootwear',
        navid:3,
        price:6789,
        image: '/assets/images/casualfootwear3.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:7,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'casualfootwear',
        navid:4,
        price:56789,
        image: '/assets/images/casualfootwear4.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
    },{
        id:7,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'casualfootwear',
        navid:5,
        price:129,
        image: '/assets/images/casualfootwear5.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:7,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'casualfootwear',
        navid:6,
        price:1234,
        image: '/assets/images/casualfootwear6.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:8,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'headphones',
        navid:1,
        price:123,
        image: '/assets/images/headphones1.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:8,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'headphones',
        navid:2,
        price:234,
        image: '/assets/images/headphones2.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:8,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'headphones',
        navid:3,
        price:3400,
        image: '/assets/images/headphones3.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:8,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'headphones',
        navid:4,
        price:1300,
        image: '/assets/images/headphones4.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:8,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'headphones',
        navid:5,
        price:1200,
        image: '/assets/images/headphones5.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:8,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'headphones',
        navid:6,
        price:890,
        image: '/assets/images/headphones6.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:9,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'makeup',
        navid:1,
        price:950,
        image: '/assets/images/makeup1.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:9,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'makeup',
        navid:2,
        price:900,
        image: '/assets/images/makeup2.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:9,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        price:800,
        navid:3,
        image: '/assets/images/makeup3.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:9,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'makeup',
        navid:4,
        price:700,
        image: '/assets/images/makeup4.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:9,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'makeup',
        navid:5,
        price:500,
        image: '/assets/images/makeup5.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },{
        id:9,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'makeup',
        navid:6,
        price:1000,
        image: '/assets/images/makeup6.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:10,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'sportshoes',
        navid:1,
        price:456,
        image: '/assets/images/sportshoes1.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:10,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'sportshoes',
        navid:2,

        price:569,
        image: '/assets/images/sportshoes2.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:10,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'sportshoes',
        navid:3,
        price:459,
        image: '/assets/images/sportshoes3.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:10,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'sportshoes',
        navid:4,
        price:460,
        image: '/assets/images/sportshoes4.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        


    },
    {
        id:10,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'sportshoes',
        navid:5,
        price:350,
        image: '/assets/images/sportshoes5.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },
    {
        id:10,
        name:'Libas',
        description:'Block Print Sraight Kurta',
        item:'sportshoes',
        navid:6,
        price:450,
        image: '/assets/images/sportshoes6.jpg',
        info:'100% Original Product Free Delivery on order above Rs. 799',
        info1:'Pay on delivery might be available Easy 30 days returns and',
        info2:'exchangesTry & Buy might be available',
        units:1,        

    },





    
    

]